name: InventoryBackup
version: '1.0.0'
main: com.zfzfg.inventorybackup.InventoryBackup
api-version: '1.20'
author: zfzfg
description: Saves player inventories on death and provides restore functionality

commands:
  inv:
    description: Inventory backup commands
    usage: /inv <player> <restore|show|givemissing> <filename> OR /inv backup <all|player>
    permission: inventorybackup.use
    aliases: [inventory, invbackup]

permissions:
  inventorybackup.use:
    description: Use all inventory backup commands
    default: op
  inventorybackup.restore:
    description: Restore inventories
    default: op
  inventorybackup.show:
    description: Show saved inventories
    default: op
  inventorybackup.givemissing:
    description: Give missing items
    default: op
  inventorybackup.backup:
    description: Create manual backups
    default: op
  inventorybackup.notify:
    description: Receive backup notification messages
    default: op
